"""Add missing models

Revision ID: 2fff20ce2c7b
Revises: fabbe5861740
Create Date: 2026-06-15 18:57:32.047177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fff20ce2c7b"
down_revision: str | None = "fabbe5861740"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE notificationtype AS ENUM ('SYSTEM', 'BOOKING', 'DISPATCH', 'SURGE', 'PROMO');")
    op.execute("CREATE TYPE notificationchannel AS ENUM ('PUSH', 'EMAIL', 'SMS', 'IN_APP');")
    op.execute("CREATE TYPE notificationstatus AS ENUM ('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED');")
    op.drop_index(
        op.f("ix_user_notification_preferences_user_id"),
        table_name="user_notification_preferences",
    )
    op.drop_table("user_notification_preferences")
    op.drop_index(
        op.f("ix_notification_deliveries_notification_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.add_column(
        "notification_templates", sa.Column("event_type", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "notification_templates",
        sa.Column("channels", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.add_column(
        "notification_templates",
        sa.Column("title_template", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "notification_templates", sa.Column("message_template", sa.Text(), nullable=False)
    )
    op.drop_index(
        op.f("ix_notification_templates_event_name"), table_name="notification_templates"
    )
    op.create_index(
        op.f("ix_notification_templates_event_type"),
        "notification_templates",
        ["event_type"],
        unique=True,
    )
    op.drop_column("notification_templates", "body_template")
    op.drop_column("notification_templates", "subject_template")
    op.drop_column("notification_templates", "event_name")
    op.drop_column("notification_templates", "channel")
    op.add_column(
        "notifications",
        sa.Column(
            "type",
            sa.Enum("SYSTEM", "BOOKING", "DISPATCH", "SURGE", "PROMO", name="notificationtype"),
            nullable=False,
        ),
    )
    op.add_column(
        "notifications",
        sa.Column(
            "channel",
            sa.Enum("PUSH", "EMAIL", "SMS", "IN_APP", name="notificationchannel"),
            nullable=False,
        ),
    )
    op.add_column("notifications", sa.Column("message", sa.Text(), nullable=False))
    op.add_column(
        "notifications", sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("notifications", sa.Column("event_id", sa.String(length=100), nullable=True))
    op.add_column("notifications", sa.Column("error_message", sa.Text(), nullable=True))
    op.execute("ALTER TABLE notifications ALTER COLUMN status TYPE notificationstatus USING status::text::notificationstatus")
    #op.alter_column(
    #    "notifications",
    #    "status",
    #    existing_type=postgresql.ENUM(
    #        "PENDING", "SENT", "FAILED", "PARTIAL", name="notification_status_enum"
    #    ),
    #    type_=sa.Enum("PENDING", "PROCESSING", "DELIVERED", "FAILED", name="notificationstatus"),
    #    existing_nullable=False,
    #)
    op.create_index(op.f("ix_notifications_event_id"), "notifications", ["event_id"], unique=False)
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.drop_column("notifications", "content")
    op.drop_column("notifications", "metadata_payload")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column(
            "metadata_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "notifications", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_event_id"), table_name="notifications")
    op.execute("ALTER TABLE notifications ALTER COLUMN status TYPE notification_status_enum USING status::text::notification_status_enum")
    #op.alter_column(
    #    "notifications",
    #    "status",
    #    existing_type=sa.Enum(
    #        "PENDING", "PROCESSING", "DELIVERED", "FAILED", name="notificationstatus"
    #    ),
    #    type_=postgresql.ENUM(
    #        "PENDING", "SENT", "FAILED", "PARTIAL", name="notification_status_enum"
    #    ),
    #    existing_nullable=False,
    #)
    op.drop_column("notifications", "error_message")
    op.drop_column("notifications", "event_id")
    op.drop_column("notifications", "data")
    op.drop_column("notifications", "message")
    op.drop_column("notifications", "channel")
    op.drop_column("notifications", "type")
    op.add_column(
        "notification_templates",
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", "PUSH", "WEBSOCKET", name="notification_channel_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "notification_templates",
        sa.Column("event_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.add_column(
        "notification_templates",
        sa.Column("subject_template", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notification_templates",
        sa.Column("body_template", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_notification_templates_event_type"), table_name="notification_templates"
    )
    op.create_index(
        op.f("ix_notification_templates_event_name"),
        "notification_templates",
        ["event_name"],
        unique=False,
    )
    op.drop_column("notification_templates", "message_template")
    op.drop_column("notification_templates", "title_template")
    op.drop_column("notification_templates", "channels")
    op.drop_column("notification_templates", "event_type")
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("notification_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", "PUSH", "WEBSOCKET", name="notification_channel_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SENT", "FAILED", "RETRYING", name="delivery_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("attempt_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_deliveries_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
    )
    op.create_index(
        op.f("ix_notification_deliveries_notification_id"),
        "notification_deliveries",
        ["notification_id"],
        unique=False,
    )
    op.create_table(
        "user_notification_preferences",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("sms_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("push_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_notification_preferences")),
    )
    op.create_index(
        op.f("ix_user_notification_preferences_user_id"),
        "user_notification_preferences",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###
