"""Phase 3 Migrations

Revision ID: a90fdf897044
Revises: 2fff20ce2c7b
Create Date: 2026-06-16 17:52:49.830944
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a90fdf897044"
down_revision: str | None = "2fff20ce2c7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "AUTHORIZED",
                "CAPTURED",
                "FAILED",
                "REFUNDED",
                name="payment_status_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("gateway_reference", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_payment_intents_booking_id_bookings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
            name=op.f("fk_payment_intents_customer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_intents")),
    )
    op.create_index(
        op.f("ix_payment_intents_booking_id"), "payment_intents", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_intents_customer_id"), "payment_intents", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_payment_intents_status"), "payment_intents", ["status"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_intent_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_intent_id"],
            ["payment_intents.id"],
            name=op.f("fk_transactions_payment_intent_id_payment_intents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        op.f("ix_transactions_payment_intent_id"),
        "transactions",
        ["payment_intent_id"],
        unique=False,
    )
    op.add_column("airports", sa.Column("city", sa.String(length=100), nullable=False))
    op.add_column("airports", sa.Column("country", sa.String(length=100), nullable=False))
    op.add_column("airports", sa.Column("latitude", sa.Float(), nullable=False))
    op.add_column("airports", sa.Column("longitude", sa.Float(), nullable=False))
    op.add_column("airports", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("airports", "is_active")
    op.drop_column("airports", "longitude")
    op.drop_column("airports", "latitude")
    op.drop_column("airports", "country")
    op.drop_column("airports", "city")
    op.drop_index(op.f("ix_transactions_payment_intent_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_payment_intents_status"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_customer_id"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_booking_id"), table_name="payment_intents")
    op.drop_table("payment_intents")
    # ### end Alembic commands ###
