"""Add Pricing and Notification Domains

Revision ID: efb62a646b61
Revises: bdfafe0b7d47
Create Date: 2026-06-15 18:42:05.364441
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'efb62a646b61'
down_revision: Union[str, None] = 'bdfafe0b7d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_estimates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_rule_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_applied', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fare_estimates'))
    )
    op.create_index(op.f('ix_fare_estimates_booking_id'), 'fare_estimates', ['booking_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_minute_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waiting_charge_per_minute', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('airport_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules'))
    )
    op.create_index(op.f('ix_pricing_rules_active'), 'pricing_rules', ['active'], unique=False)
    op.create_index(op.f('ix_pricing_rules_city'), 'pricing_rules', ['city'], unique=False)
    op.create_index(op.f('ix_pricing_rules_vehicle_type'), 'pricing_rules', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_rules_vehicle_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_city'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_active'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_fare_estimates_booking_id'), table_name='fare_estimates')
    op.drop_table('fare_estimates')
    # ### end Alembic commands ###
